# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/MVLidarImplementation',
                'doc_host': 'https://alunos-pfc.github.io',
                'git_url': 'https://github.com/alunos-pfc/MVLidarImplementation',
                'lib_path': 'MVLidarImplementation'},
  'syms': {'MVLidarImplementation.core': {'MVLidarImplementation.core.foo': ('core.html#foo', 'MVLidarImplementation/core.py')}}}
