# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_data.ipynb.

# %% auto 0
__all__ = ['train_path', 'test_path', 'Dataset', 'foo']

# %% ../nbs/00_data.ipynb 2
import torch
import numpy as np
from torch.utils.data import Dataset

# %% ../nbs/00_data.ipynb 3
train_path = "yourpathhere"

test_path = "yourpathhere"

# %% ../nbs/00_data.ipynb 4
class Dataset(Dataset):
    def __init__(self, image_folder_path, mask_folder_path, transform=None):
        self.image_folder_path = image_folder_path
        self.mask_folder_path = mask_folder_path
        self.transform = transform
        self.image_filenames = os.listdir(image_folder_path)
        self.mask_filenames = os.listdir(mask_folder_path)

    def __len__(self):
        return len(self.image_filenames)

    def __getitem__(self, idx):
        img_name = os.path.join(self.image_folder_path, self.image_filenames[idx])
        mask_name = os.path.join(self.mask_folder_path, self.mask_filenames[idx])

        image = Image.open(img_name)
        mask = Image.open(mask_name)

        if self.transform:
            image = self.transform(image)
            mask = self.transform(mask)

        return image, mask

# %% ../nbs/00_data.ipynb 5
def foo():
    a=10
    return a
